extern Vtx rmap_sdm_rmap_sdm_mesh_vtx_0[4];
extern Gfx rmap_sdm_rmap_sdm_mesh_tri_0[];
extern Vtx rmap_sdm_rmap_sdm_mesh_vtx_1[8];
extern Gfx rmap_sdm_rmap_sdm_mesh_tri_1[];
extern Gfx mat_rmap_sdm_map_mat_1_layer1[];
extern Gfx mat_revert_rmap_sdm_map_mat_1_layer1[];
extern Gfx mat_rmap_sdm_map_mat_3_layer1[];
extern Gfx mat_revert_rmap_sdm_map_mat_3_layer1[];
extern Gfx rmap_sdm_rmap_sdm_mesh[];
