extern const GeoLayout rf_ramp_geo[];
extern u8 rf_ramp_arrow_ci8[];
extern u8 rf_ramp_arrow_pal_rgba16[];
extern u8 rf_ramp_rainbowembriodeier_rgba16[];
extern Vtx rf_ramp_rf_ramp_mesh_layer_1_vtx_0[23];
extern Gfx rf_ramp_rf_ramp_mesh_layer_1_tri_0[];
extern Vtx rf_ramp_rf_ramp_mesh_layer_1_vtx_1[67];
extern Gfx rf_ramp_rf_ramp_mesh_layer_1_tri_1[];
extern Gfx mat_rf_ramp_arrow[];
extern Gfx mat_revert_rf_ramp_arrow[];
extern Gfx mat_rf_ramp_rainbowembroidery[];
extern Gfx mat_revert_rf_ramp_rainbowembroidery[];
extern Gfx rf_ramp_rf_ramp_mesh_layer_1[];
