#include "src/game/envfx_snow.h"

const GeoLayout temple_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, temple_dl_0zroom_geo),
			GEO_BRANCH(1, temple_dl_1room_geo),
		GEO_CLOSE_NODE(),
		GEO_ASM(0, geo_render_preview_mario),
		GEO_ASM(0, geo_render_game_title),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout temple_dl_0zroom_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout temple_dl_1room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_breakroom1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_breakroom1_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_breakroom2_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -7119, 2169, -17429, temple_dl_grindr_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_grindr_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, temple_dl_grindr_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room1_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room1_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room1_midsection_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room1_midsection_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room1_midsection_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room1_midsection_2_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room1_midsection_2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room2_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room3_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room3_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room3_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room3_entry_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room3_entry_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room4_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room4_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room4_92_midsection_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room4_92_midsection_003_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room5_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room5_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room5_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room5_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room5_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, temple_dl_vis_room5_001_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room5_midsection_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room5_midsection_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room5_midsection_2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room5_midsection_2_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room5_midsection_2_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room6_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room6_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room6_midsection_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room6_midsection_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room6_midsection_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room7_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room7_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room7_001_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room8_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room8_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room9_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, temple_dl_vis_room9_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room9_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room9_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room91_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room91_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room92_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room92_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room_94_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room_94_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room_94_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room_95_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room_95_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room_96_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room_96_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_room_97_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room_97_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -12864, 3799, -199, temple_dl_vis_room_99_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, temple_dl_vis_room_99_mesh_layer_5),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_room_99_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_wigger_hall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_wigger_hall_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_vis_wigger_hall_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_wigger_hall_001_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3880, 4061, -199, temple_dl_vis_wigger_hall_002_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_vis_wigger_hall_002_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -17396, 2303, -21110, temple_dl_visMiningDrill_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_visMiningDrill_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -9740, 1406, -8161, 0, -15, 0, temple_dl_visMiningDrill_002_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_visMiningDrill_002_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_ALPHA, temple_dl_final_revert_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, temple_dl_final_revert_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout temple_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, temple_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
