extern Vtx rmaphall_rmaphall_mesh_vtx_0[4];
extern Gfx rmaphall_rmaphall_mesh_tri_0[];
extern Vtx rmaphall_rmaphall_mesh_vtx_1[8];
extern Gfx rmaphall_rmaphall_mesh_tri_1[];
extern Gfx mat_rmaphall_map_mat_1_layer1[];
extern Gfx mat_revert_rmaphall_map_mat_1_layer1[];
extern Gfx mat_rmaphall_map_mat_3_layer1[];
extern Gfx mat_revert_rmaphall_map_mat_3_layer1[];
extern Gfx rmaphall_rmaphall_mesh[];
