extern const GeoLayout finalboss_area_1_geo[];
extern const GeoLayout finalboss_dl_room1_geo[];
extern const GeoLayout finalboss_area_1[];
extern const Collision finalboss_area_1_collision[];
extern const u8 finalboss_area_1_collision_rooms[];
extern const MacroObject finalboss_area_1_macro_objs[];
extern u8 finalboss_dl_biotech_pillar_ci8[];
extern u8 finalboss_dl_biotech_pillar_pal_rgba16[];
extern u8 finalboss_dl_gross_top_ci8[];
extern u8 finalboss_dl_gross_top_pal_rgba16[];
extern u8 finalboss_dl_HoleySpike_i8[];
extern u8 finalboss_dl_gakeside_i8[];
extern u8 finalboss_dl_Blood_i8[];
extern Vtx finalboss_dl_Cylinder_010_mesh_layer_1_vtx_0[36];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_1_tri_0[];
extern Vtx finalboss_dl_Cylinder_010_mesh_layer_1_vtx_1[16];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_1_tri_1[];
extern Vtx finalboss_dl_Cylinder_010_mesh_layer_1_vtx_2[156];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_1_tri_2[];
extern Vtx finalboss_dl_Cylinder_010_mesh_layer_1_vtx_3[100];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_1_tri_3[];
extern Vtx finalboss_dl_Cylinder_010_mesh_layer_5_vtx_0[100];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_5_tri_0[];
extern Gfx mat_finalboss_dl_BioTechPillar[];
extern Gfx mat_revert_finalboss_dl_BioTechPillar[];
extern Gfx mat_finalboss_dl_gross_top[];
extern Gfx mat_revert_finalboss_dl_gross_top[];
extern Gfx mat_finalboss_dl_holey_spike[];
extern Gfx mat_revert_finalboss_dl_holey_spike[];
extern Gfx mat_finalboss_dl_gake_wall[];
extern Gfx mat_revert_finalboss_dl_gake_wall[];
extern Gfx mat_finalboss_dl_blood[];
extern Gfx mat_revert_finalboss_dl_blood[];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_1[];
extern Gfx finalboss_dl_Cylinder_010_mesh_layer_5[];
