#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"
#include "king_bobomb/geo.inc.c"
#include "wiggler_body/geo.inc.c"
#include "wiggler_head/geo.inc.c"

#include "chest/geo.inc.c"
#include "hover/geo.inc.c"
#include "cchest/geo.inc.c"
#include "woman/geo.inc.c"
#include "save/geo.inc.c"
#include "module3d/geo.inc.c"
#include "ice/geo.inc.c"
#include "mchest/geo.inc.c"
#include "key/geo.inc.c"
#include "silver_star/geo.inc.c"
#include "utilityMace/geo.inc.c"
#include "utilityFlame/geo.inc.c"
#include "car/geo.inc.c"
#include "live/geo.inc.c"
#include "gshredder/geo.inc.c"
#include "gravity_crystal/geo.inc.c"
#include "oldmap/geo.inc.c"
#include "lavawall/geo.inc.c"
