extern Vtx rmapvanishhop_rmapvanishhop_mesh_vtx_0[4];
extern Gfx rmapvanishhop_rmapvanishhop_mesh_tri_0[];
extern Vtx rmapvanishhop_rmapvanishhop_mesh_vtx_1[8];
extern Gfx rmapvanishhop_rmapvanishhop_mesh_tri_1[];
extern Gfx mat_rmapvanishhop_map_mat_1_layer1[];
extern Gfx mat_revert_rmapvanishhop_map_mat_1_layer1[];
extern Gfx mat_rmapvanishhop_map_mat_3_layer1[];
extern Gfx mat_revert_rmapvanishhop_map_mat_3_layer1[];
extern Gfx rmapvanishhop_rmapvanishhop_mesh[];
