extern Vtx rmap_maze_rmap_maze_mesh_vtx_0[4];
extern Gfx rmap_maze_rmap_maze_mesh_tri_0[];
extern Vtx rmap_maze_rmap_maze_mesh_vtx_1[16];
extern Gfx rmap_maze_rmap_maze_mesh_tri_1[];
extern Gfx mat_rmap_maze_map_mat_1_layer1[];
extern Gfx mat_revert_rmap_maze_map_mat_1_layer1[];
extern Gfx mat_rmap_maze_map_mat_3_layer1[];
extern Gfx mat_revert_rmap_maze_map_mat_3_layer1[];
extern Gfx rmap_maze_rmap_maze_mesh[];
