#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "header.h"

#include "geo.inc.c"
#include "minijunc/geo.inc.c"
#include "smallhall/geo.inc.c"
#include "doorhole/geo.inc.c"
#include "doorhole_covered/geo.inc.c"
#include "rlobby/geo.inc.c"
#include "rtresure/geo.inc.c"
#include "rwalljump/geo.inc.c"
#include "rlongjump/geo.inc.c"
#include "carpetPoint/geo.inc.c"
#include "vanishhop/geo.inc.c"
#include "rfnab/geo.inc.c"
#include "rbtcm/geo.inc.c"
#include "baldi/geo.inc.c"
#include "baldidoor/geo.inc.c"
#include "rboxes/geo.inc.c"
#include "spaceworld/geo.inc.c"
#include "facade1/geo.inc.c"
#include "rgardenhall/geo.inc.c"
#include "rfurnace/geo.inc.c"
#include "dungeondoor/geo.inc.c"
#include "rgrindr/geo.inc.c"
#include "rcavejump/geo.inc.c"
#include "rsplithall/geo.inc.c"
#include "rmaze/geo.inc.c"
#include "rsupertreasure/geo.inc.c"
#include "rsilverpillar/geo.inc.c"
#include "rbns/geo.inc.c"
#include "rclock/geo.inc.c"
#include "dungeonclockhand/geo.inc.c"
