#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

u16 gDungeonTextureBrick[4096] = {0};
u16 gDungeonTextureCarpet[2048] = {0};
u16 gDungeonTextureTile[2048] = {0};
u16 gDungeonTextureAltWall[4096] = {0};
u16 gDungeonTextureShingles[2048] = {0};

#include "make_const_nonconst.h"

#include "leveldata.inc.c"
#include "minijunc/collision.inc.c"
#include "minijunc/model.inc.c"
#include "smallhall/collision.inc.c"
#include "smallhall/model.inc.c"
#include "doorhole/collision.inc.c"
#include "doorhole/model.inc.c"
#include "doorhole_covered/collision.inc.c"
#include "doorhole_covered/model.inc.c"
#include "rlobby/collision.inc.c"
#include "rlobby/model.inc.c"
#include "rtresure/collision.inc.c"
#include "rtresure/model.inc.c"
#include "rwalljump/collision.inc.c"
#include "rwalljump/model.inc.c"
#include "rlongjump/collision.inc.c"
#include "rlongjump/model.inc.c"
#include "carpetPoint/collision.inc.c"
#include "carpetPoint/model.inc.c"
#include "vanishhop/collision.inc.c"
#include "vanishhop/model.inc.c"
#include "rfnab/collision.inc.c"
#include "rfnab/model.inc.c"
#include "rbtcm/collision.inc.c"
#include "rbtcm/model.inc.c"
#include "baldi/collision.inc.c"
#include "baldi/model.inc.c"
#include "baldidoor/model.inc.c"
#include "texgensamples/model.inc.c"
#include "rboxes/model.inc.c"
#include "rboxes/collision.inc.c"
#include "spaceworld/collision.inc.c"
#include "spaceworld/model.inc.c"
#include "facade1/model.inc.c"
#include "facade1/collision.inc.c"
#include "rgardenhall/collision.inc.c"
#include "rgardenhall/model.inc.c"
#include "rfurnace/collision.inc.c"
#include "rfurnace/model.inc.c"
#include "rmapjunc/model.inc.c"
#include "rmaphall/model.inc.c"
#include "rmaplobby/model.inc.c"
#include "rmapfacade1/model.inc.c"
#include "rmaptreasure/model.inc.c"
#include "rmapspaceworld/model.inc.c"
#include "rmapgarden/model.inc.c"
#include "rmapwallkick/model.inc.c"
#include "rmapvanishhop/model.inc.c"
#include "rzmapigzag/model.inc.c"
