extern Vtx rmappush_rmappush_mesh_vtx_0[11];
extern Gfx rmappush_rmappush_mesh_tri_0[];
extern Vtx rmappush_rmappush_mesh_vtx_1[20];
extern Gfx rmappush_rmappush_mesh_tri_1[];
extern Gfx mat_rmappush_map_mat_1_layer1[];
extern Gfx mat_revert_rmappush_map_mat_1_layer1[];
extern Gfx mat_rmappush_map_mat_3_layer1[];
extern Gfx mat_revert_rmappush_map_mat_3_layer1[];
extern Gfx rmappush_rmappush_mesh[];
