#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "header.h"

#include "geo.inc.c"
#include "rf_straight/geo.inc.c"
#include "rf_right/geo.inc.c"
#include "rf_left/geo.inc.c"
#include "rf_ramp/geo.inc.c"
#include "rf_spinner/geo.inc.c"
#include "rf_tilting/geo.inc.c"
#include "rf_tilting_obj/geo.inc.c"
#include "rf_squarish/geo.inc.c"
#include "rf_squarish_obj/geo.inc.c"
#include "rf_amplected/geo.inc.c"
#include "rf_rino/geo.inc.c"
#include "rf_rino_obj/geo.inc.c"
#include "rf_rino_plat/geo.inc.c"
#include "rf_slope/geo.inc.c"
#include "rf_blankjump/geo.inc.c"
#include "rf_vertical/geo.inc.c"
