extern const GeoLayout gameover_area_1_geo[];
extern const GeoLayout gameover_area_1[];
extern const Collision gameover_area_1_collision[];
extern const MacroObject gameover_area_1_macro_objs[];
extern u8 gameover_dl_earth_rgba16[];
extern u8 gameover_dl_dai_rgba16[];
extern u8 gameover_dl_WorldEndFlames_ci8[];
extern u8 gameover_dl_WorldEndFlames_pal_rgba16[];
extern Vtx gameover_dl_Icosphere_mesh_layer_1_vtx_0[256];
extern Gfx gameover_dl_Icosphere_mesh_layer_1_tri_0[];
extern Vtx gameover_dl_Icosphere_mesh_layer_1_vtx_1[248];
extern Gfx gameover_dl_Icosphere_mesh_layer_1_tri_1[];
extern Vtx gameover_dl_Icosphere_mesh_layer_1_vtx_2[90];
extern Gfx gameover_dl_Icosphere_mesh_layer_1_tri_2[];
extern Gfx mat_gameover_dl_f3dlite_material_002[];
extern Gfx mat_revert_gameover_dl_f3dlite_material_002[];
extern Gfx mat_gameover_dl_f3dlite_material_006[];
extern Gfx mat_revert_gameover_dl_f3dlite_material_006[];
extern Gfx mat_gameover_dl_f3dlite_material_007[];
extern Gfx mat_revert_gameover_dl_f3dlite_material_007[];
extern Gfx gameover_dl_Icosphere_mesh_layer_1[];
