#include "levels/pitstop/area_1/collision.inc.c"
#include "levels/pitstop/area_1/room.inc.c"
#include "levels/pitstop/area_1/macro.inc.c"
#include "levels/pitstop/area_1/spline.inc.c"
#include "levels/pitstop/model.inc.c"
