#include "levels/rogue/rmemorize/texscroll.inc.h"
#include "levels/rogue/rthwomps/texscroll.inc.h"
#include "levels/rogue/rfacade2/texscroll.inc.h"
#include "levels/rogue/rboss/texscroll.inc.h"
#include "levels/rogue/rcavejump/texscroll.inc.h"
#include "levels/rogue/rfurnace/texscroll.inc.h"
#include "levels/rogue/rgardenhall/texscroll.inc.h"
#include "levels/rogue/facade1/texscroll.inc.h"
#include "levels/rogue/vanishhop/texscroll.inc.h"
#include "levels/rogue/rbtcm/texscroll.inc.h"
#include "levels/rogue/rfnab/texscroll.inc.h"
extern void scroll_textures_rogue();
