extern Vtx rmapcavejump_rmapcavejump_mesh_vtx_0[32];
extern Gfx rmapcavejump_rmapcavejump_mesh_tri_0[];
extern Vtx rmapcavejump_rmapcavejump_mesh_vtx_1[70];
extern Gfx rmapcavejump_rmapcavejump_mesh_tri_1[];
extern Gfx mat_rmapcavejump_map_mat_1_layer1[];
extern Gfx mat_revert_rmapcavejump_map_mat_1_layer1[];
extern Gfx mat_rmapcavejump_map_mat_3_layer1[];
extern Gfx mat_revert_rmapcavejump_map_mat_3_layer1[];
extern Gfx rmapcavejump_rmapcavejump_mesh[];
